services:
  dol:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # 存档目录映射
      - ./save:/save
      # 游戏目录映射
      - ./game:/game
      # 存档备份目录
      - ./backup:/backup
      # 服务配置
      - ./dol_save_server.toml:/dol_save_server.toml
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
