# 游戏配置, 可同时配置多个
[[game]]
# 游戏名称 不能包含斜杠或反斜杠
name = "dol"

# 游戏目录
root = "/game"

# 访问"/"时的默认文件名
index = "Degrees of Lewdity.html"

# 存档保存目录
save_dir = "/save"

# 启用时检查和修改"modList.json", 并更新存档模组
init_mod = true

# 服务配置
[server]
# 服务地址
# 如果需要局域网的其他设备访问, 则需要将IP地址修改为本机的局域网地址或直接使用`0.0.0.0`绑定本机所有地址
bind = "0.0.0.0:5000"

# 是否允许存档相关接口跨域访问
# **注意:**
# - 若该功能和`auth`同时启用, 则`tls`功能也需要同步启用才能正常访问跨域请求
# - 启用时不允许配置多个游戏
cors = false

# 访问黑名单 参数为正则表达式 忽略大小写
blacklist = [
    ".*\\.toml",
]

# 是否启用PWA功能
# PWA 仅在`localhost`下或启用`tls`(且CA必须为系统信任的)时有效
pwa_enabled = false

# TLS 相关配置
[server.tls]
# 是否启用
enable = false
key = """
替换为你的证书密钥 PEM格式
"""
cert = """
替换为你的证书CERT PEM格式
"""

# 用户验证相关配置
[auth]
# 是否启用
# 启用后存档会保存在以用户名命名文件夹中, 不同用户之间的存档不共通
enable = false

# 是否所有页面都需要登入才能查看
#
# - 为`true`时`除登录和`PWA`的外其他请求都需要登入
# - 为`false`是仅`/api/`开头的请求需要登入
global = false

# 用户配置 如果需要添加用户, 则按照以下格式在此处添加
# [[auth.users]]
# username = "用户名"
# password = "密码"
[[auth.users]]
# 用户名
# 注意: 用户名应为运行系统的合法目录路径, 否则可能导致存档保存失败
username = "anonymous"
# 密码
password = ""

# 定时备份
[backup]
enable = true
# 邮件标题
title = "存档备份"
# 备份周期 从服务启动开始计算 默认为1小时 格式见 https://crates.io/crates/duration-str
period = "1h"
# 是否在启动时无条件触发一次备份
backup_on_start = true
# 备份方式 目前有以下方式
# `Fs`: 备份到指定目录 默认值
# `Mail`: 邮件备份
type = "Fs"
# 以下为`Fs`参数
# 备份目录
dir = "backup"
# 以下为`Mail`参数
# 发件服务器地址
# smtp_host = "stmp.example.com"
# 发件服务器端口
# smtp_port = 456
# 用户名
# username = "username"
# 密码
# password = "password"
# 发件人邮箱
# sender = "sender@example.com"
# 收件人邮箱
# receiver = ["receiver1@example.com", ...]
